version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-net

  unit:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app-net
    entrypoint: ["npm", "test"]

  e2e:
    build:
      context: .
      dockerfile: Dockerfile.e2e
    depends_on:
      - web
    networks:
      - app-net
    environment:
      - CYPRESS_baseUrl=http://web:3000
    entrypoint: ["npx", "cypress", "run", "--config", "baseUrl=http://web:3000"]

networks:
  app-net:
    driver: bridge

