version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-webapp_web   # ←✅ 追加！（必ずこの名前でビルドされる）
    ports:
      - "3000:3000"
    networks:
      - app-net

  unit:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-webapp_unit   # ←✅ 追加！（単体テスト用）
    networks:
      - app-net
    entrypoint: ["npm", "test"]

  e2e:
    build:
      context: .
      dockerfile: Dockerfile.e2e
    image: my-webapp_e2e    # ←✅ 追加！（E2Eテスト用）
    depends_on:
      - web
    networks:
      - app-net
    environment:
      - CYPRESS_baseUrl=http://web:3000
    entrypoint: ["npx", "cypress", "run", "--config", "baseUrl=http://web:3000"]

networks:
  app-net:
    driver: bridge
