version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "3000:3000"
    networks:
      - default

  e2e:
    build:
      context: .
      dockerfile: Dockerfile.e2e
    depends_on:
      - web
    networks:
      - default
    environment:
      - CYPRESS_baseUrl=http://web:3000
    entrypoint: ["npx", "cypress", "run", "--config", "baseUrl=http://web:3000"]

  unit:
    build:
      context: .
      dockerfile: Dockerfile.web
    networks:
      - default
    entrypoint: ["npm", "test"]

networks:
  default:
    driver: bridge
