name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: Node.jsをセットアップ
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 依存パッケージインストール
        run: npm install

      - name: テスト実行
        run: npm run test

  deploy:
    needs: build-and-test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Renderにデプロイする
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
