name: CI

name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  docker-compose-ci:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: Docker Composeビルド＆テスト
        run: |
          docker compose version
          docker compose build
          docker compose up --abort-on-container-exit --exit-code-from unit

      - name: Dockerログイン＆Push（GitHub Packages）
        env:
          CR_PAT: ${{ secrets.CR_PAT }}
        run: |
          echo $CR_PAT | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker tag my-webapp_web ghcr.io/${{ github.repository }}:latest
          docker push ghcr.io/${{ github.repository }}:latest

  deploy-production:
    needs: docker-compose-ci
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Renderに本番デプロイ
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
          
# deploy-staging:
#   needs: build-test-e2e
#   if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
#   runs-on: ubuntu-latest
#   steps:
#     - name: Renderにステージングデプロイ
#       run: |
#         curl -X POST ${{ secrets.RENDER_STG_DEPLOY_HOOK_URL }}
