name: Docker CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Docker Compose でビルド
        run: docker compose build

      - name: Dockerでユニットテスト
        run: docker compose run --rm web npm test

      # - name: サーバー起動（E2E用）
      #   run: docker-compose up -d

      # - name: サーバーが立ち上がるのを待つ（E2E用）
      #   run: npx wait-on http://localhost:3000

      # - name: E2Eテスト実行（必要なら）
      #   run: docker-compose run --rm web npm run test:e2e

      # - name: カバレッジレポート生成（任意）
      #   run: docker-compose run --rm web npm run coverage:report

      - name: ビルド後のクリーンアップ
        run: docker compose down --volumes --remove-orphans
