name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: Node.js セットアップ
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: 依存関係インストール
        run: npm install

      - name: ユニットテスト（カバレッジ付き）
        run: npm test -- --coverage

      - name: サーバー起動
        run: npm start &
        
      - name: サーバーが立ち上がるのを待つ
        run: npx wait-on http://localhost:3000

      - name: E2Eテストの実行
        run: npm run test:e2e

      - name: カバレッジレポートの生成
        run: npm run coverage:report
