name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-test-e2e:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: Node.jsをセットアップ
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: 依存関係をインストール
        run: npm install

      - name: wait-onをインストール
        run: npm install -g wait-on

      - name: サーバーをバックグラウンドで起動して待機
        run: |
          npm start &
          wait-on http://localhost:3000

      - name: 単体テスト・統合テストを実行
        run: npm run test

      - name: E2Eテストを実行
        run: npm run test:e2e

      - name: ビルド（必要なら）
        run: npm run build

  deploy-production:
    needs: build-test-e2e
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Renderに本番デプロイ
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
          
#  deploy-staging:
#    needs: build-test-e2e
#    if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
#    runs-on: ubuntu-latest
#    steps:
#      - name: Renderにステージングデプロイ
#        run: |
#          curl -X POST ${{ secrets.RENDER_STG_DEPLOY_HOOK_URL }}
